### ISSUE TITLE
Please help!!

### ISSUE THREAD

**Issue by GetRektBoy724** [roccomuso/netrat#7]
When i run netrat it show up like this:
root@localhost:/home/root324/netrat# netrat
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'mustache'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/netrat/lib/builder.js:8:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
root@localhost:/home/root324/netrat#

**Comment by roccomuso** [comment]
How did you run it?
Did you clone the github repository?

you must do a `npm install` inside the folder to install required dependencies.
